import type {
  ActivityEvent,
  Agent,
  ApprovalItem,
  AuditEvent,
  Department,
  Goal,
  OracleSuggestion,
  Skill,
  Workflow,
  Workspace,
} from "./types";

export const workspaces: Workspace[] = [
  {
    id: "ws-ferhan-core",
    name: "Ferhan · Core",
    shortName: "FC",
    industry: "Kişisel / Çekirdek Ekip",
    mission: "Günlük dijital operasyonumu 10x kaldıraçla çalıştırmak.",
    vision:
      "İnsan emeğinin yalnızca yargı, onay ve strateji için harcandığı; kalan her şeyin agent'lar tarafından yürütüldüğü bir çekirdek ekip.",
    strategicThemes: [
      {
        id: "st-1",
        label: "Operasyonel Kaldıraç",
        description: "Her tekrarlayan işin bir skill'i veya workflow'u olsun.",
        weight: 90,
      },
      {
        id: "st-2",
        label: "Dijital Egemenlik",
        description: "Sistem Git'te, veriler benim kontrolümde, her karar denetlenebilir.",
        weight: 70,
      },
      {
        id: "st-3",
        label: "Ürünleşme",
        description: "Çerçeveyi 3. müşteriye satılabilir pakete çevirmek.",
        weight: 55,
      },
    ],
    valueAnchors: [
      {
        id: "va-1",
        label: "İnsan son kararı verir",
        description: "external-send scope'u her zaman onay gerektirir.",
      },
      {
        id: "va-2",
        label: "PR disiplini",
        description: "Tüm değişiklikler review'dan geçer; şifai değişiklik yok.",
      },
      {
        id: "va-3",
        label: "Ölçülmeyen şey yok",
        description: "Her skill'in golden testi, her hedefin yörüngesi olur.",
      },
    ],
    accent: "ion",
    createdAt: "2026-02-01T00:00:00Z",
  },
  {
    id: "ws-trading-desk",
    name: "Trading Desk",
    shortName: "TD",
    industry: "Finans / Kripto & Endeks",
    mission: "Manuel mum sayma emeğini sıfıra indirmek; insan sadece stratejik kararda kalmak.",
    vision: "Paper-first, risk-disiplinli, tam otomatik brief üreten bir trading masası.",
    strategicThemes: [
      {
        id: "st-t1",
        label: "Risk-Önce",
        description: "Her sinyal önce paper modda test edilir.",
        weight: 95,
      },
      {
        id: "st-t2",
        label: "Veri Kalitesi",
        description: "İki provider fallback; tek kaynağa bağlı kalmamak.",
        weight: 80,
      },
    ],
    valueAnchors: [
      {
        id: "va-t1",
        label: "Kill-switch her zaman bir tık uzakta",
        description: "Otomasyon insan kontrolünün yerine geçmez.",
      },
    ],
    accent: "quantum",
    createdAt: "2026-02-18T00:00:00Z",
  },
  {
    id: "ws-content-studio",
    name: "Content Studio",
    shortName: "CS",
    industry: "İçerik / Araştırma",
    mission: "Fikirden yayına giden süreyi %70 kısaltmak.",
    vision: "Editör-önce-sonra disiplinini koruyan, haftalık yayın temposu yüksek içerik fabrikası.",
    strategicThemes: [
      {
        id: "st-c1",
        label: "İçerik Liderliği",
        description: "Sektörde başvurulan 3 markadan biri olmak.",
        weight: 85,
      },
      {
        id: "st-c2",
        label: "Editör Disiplini",
        description: "Agent taslağı son halini asla belirlemez.",
        weight: 90,
      },
    ],
    valueAnchors: [
      {
        id: "va-c1",
        label: "Orijinallik her zaman önce",
        description: "Başka yerden kopyalanmış izlenim veren içerik yayınlanmaz.",
      },
    ],
    accent: "nebula",
    createdAt: "2026-03-05T00:00:00Z",
  },
];

export const departments: Department[] = [
  // Ferhan · Core
  {
    id: "dept-exec",
    workspaceId: "ws-ferhan-core",
    name: "Executive",
    description: "Haftalık exec review, KPI konsolidasyonu, stratejik hiza.",
    owner: "Ferhan Y.",
    health: 94,
  },
  {
    id: "dept-ops",
    workspaceId: "ws-ferhan-core",
    name: "Operations",
    description: "Sprint ritmi, toplantı çıktıları, SOP çalıştırma.",
    owner: "Ferhan Y.",
    health: 88,
  },
  {
    id: "dept-sales",
    workspaceId: "ws-ferhan-core",
    name: "Sales & CRM",
    description: "Lead triage, outreach taslağı, pipeline raporlama.",
    owner: "Ferhan Y.",
    health: 71,
  },
  // Trading Desk
  {
    id: "dept-trading-research",
    workspaceId: "ws-trading-desk",
    name: "Research",
    description: "Piyasa taraması, haber sentezi, makro raporları.",
    owner: "Ferhan Y.",
    health: 92,
  },
  {
    id: "dept-trading-exec",
    workspaceId: "ws-trading-desk",
    name: "Execution (Paper)",
    description: "TradingView alert → paper trade kaydı ve haftalık PnL analizi.",
    owner: "Ferhan Y.",
    health: 83,
  },
  // Content Studio
  {
    id: "dept-content-research",
    workspaceId: "ws-content-studio",
    name: "Research",
    description: "Çok-kaynaklı araştırma sentezi, brief üretimi.",
    owner: "Ferhan Y.",
    health: 81,
  },
  {
    id: "dept-content-editorial",
    workspaceId: "ws-content-studio",
    name: "Editorial",
    description: "Uzun form taslak, düzenleme, yayın takvimi.",
    owner: "Ferhan Y.",
    health: 76,
  },
];

export const agents: Agent[] = [
  {
    id: "agent-orchestrator",
    workspaceId: "ws-ferhan-core",
    departmentId: "dept-exec",
    name: "orchestrator",
    displayName: "Orchestrator",
    description:
      "Ana agent. Kullanıcı niyetini plana çevirir, Task aracıyla alt ajanlara delege eder, sonuçları konsolide eder.",
    model: "opus",
    status: "live",
    scopes: ["read", "write"],
    skillIds: [],
    callsToday: 42,
    successRate: 0.97,
  },
  {
    id: "agent-business-exec",
    workspaceId: "ws-ferhan-core",
    departmentId: "dept-exec",
    name: "business-exec",
    displayName: "Business Exec",
    description: "Haftalık exec review'u dört domainden fan-out veriyle sentezler.",
    model: "opus",
    status: "idle",
    scopes: ["read", "write"],
    skillIds: ["skill-weekly-biz"],
    callsToday: 3,
    successRate: 0.93,
  },
  {
    id: "agent-ops-coordinator",
    workspaceId: "ws-ferhan-core",
    departmentId: "dept-ops",
    name: "ops-coordinator",
    displayName: "Ops Coordinator",
    description: "Sprint sağlığı, toplantı notları, SOP çalıştırma.",
    model: "sonnet",
    status: "live",
    scopes: ["read", "write"],
    skillIds: ["skill-meeting-notes"],
    callsToday: 11,
    successRate: 0.89,
  },
  {
    id: "agent-sales-assistant",
    workspaceId: "ws-ferhan-core",
    departmentId: "dept-sales",
    name: "sales-assistant",
    displayName: "Sales Assistant",
    description: "Lead enrichment, outreach taslağı, pipeline raporu.",
    model: "sonnet",
    status: "idle",
    scopes: ["read", "write", "external-send"],
    skillIds: ["skill-lead-enrichment"],
    callsToday: 6,
    successRate: 0.82,
  },
  {
    id: "agent-trading-analyst",
    workspaceId: "ws-trading-desk",
    departmentId: "dept-trading-research",
    name: "trading-analyst",
    displayName: "Trading Analyst",
    description: "Piyasa özeti, sinyal yorumlama, portföy raporu. Paper mod.",
    model: "sonnet",
    status: "live",
    scopes: ["read", "write"],
    skillIds: ["skill-market-pulse"],
    callsToday: 14,
    successRate: 0.95,
  },
  {
    id: "agent-content-producer",
    workspaceId: "ws-content-studio",
    departmentId: "dept-content-research",
    name: "content-producer",
    displayName: "Content Producer",
    description: "Araştırma sentezi, blog/rapor taslakları.",
    model: "sonnet",
    status: "paused",
    scopes: ["read", "write"],
    skillIds: ["skill-research-synthesis"],
    callsToday: 0,
    successRate: 0.87,
  },
];

export const skills: Skill[] = [
  {
    id: "skill-weekly-biz",
    workspaceId: "ws-ferhan-core",
    ownerAgentId: "agent-business-exec",
    name: "weekly-biz-review",
    displayName: "Weekly Biz Review",
    triggers: ["haftalık exec", "cuma review", "yönetim özeti"],
    description: "Tüm domain'lerden veri çeker, exec dashboard üretir.",
    runsThisWeek: 1,
    goldenTestPassing: true,
  },
  {
    id: "skill-meeting-notes",
    workspaceId: "ws-ferhan-core",
    ownerAgentId: "agent-ops-coordinator",
    name: "meeting-notes-synthesizer",
    displayName: "Meeting Notes Synthesizer",
    triggers: ["toplantı özeti", "transcript", "aksiyon çıkar"],
    description: "Toplantı transkriptini aksiyon listesine çevirir.",
    runsThisWeek: 7,
    goldenTestPassing: true,
  },
  {
    id: "skill-lead-enrichment",
    workspaceId: "ws-ferhan-core",
    ownerAgentId: "agent-sales-assistant",
    name: "lead-enrichment",
    displayName: "Lead Enrichment",
    triggers: ["yeni lead", "formdan geldi", "zenginleştir"],
    description: "Yeni lead'in CRM profilini halka açık veriyle zenginleştirir.",
    runsThisWeek: 23,
    goldenTestPassing: false,
  },
  {
    id: "skill-market-pulse",
    workspaceId: "ws-trading-desk",
    ownerAgentId: "agent-trading-analyst",
    name: "market-pulse-report",
    displayName: "Market Pulse Report",
    triggers: ["günlük brief", "piyasa özeti", "morning pulse"],
    description: "Fiyat + haber + sinyal sentezini Slack brief'ine çevirir.",
    runsThisWeek: 5,
    goldenTestPassing: true,
  },
  {
    id: "skill-research-synthesis",
    workspaceId: "ws-content-studio",
    ownerAgentId: "agent-content-producer",
    name: "research-synthesis",
    displayName: "Research Synthesis",
    triggers: ["araştırma özeti", "brief üret", "kaynak sentezi"],
    description: "Çok-kaynaklı araştırmayı tek brief'e dönüştürür.",
    runsThisWeek: 4,
    goldenTestPassing: true,
  },
];

export const workflows: Workflow[] = [
  {
    id: "wf-daily-market-briefing",
    workspaceId: "ws-trading-desk",
    departmentId: "dept-trading-research",
    name: "daily-market-briefing",
    cadence: "Hafta içi · 08:30 TR",
    nextRun: "Yarın 08:30",
    lastStatus: "success",
    steps: 3,
    description: "Her sabah hafta içi 08:30'da piyasa nabzı Slack'e düşer.",
    trigger: {
      kind: "schedule",
      cron: "30 8 * * 1-5",
      timezone: "Europe/Istanbul",
    },
    stepsDetail: [
      {
        id: "s1",
        kind: "integration",
        label: "Fiyat verisi çek",
        integration: "ccxt",
        note: "BTC, ETH, SPY, QQQ · son 24 saat",
      },
      {
        id: "s2",
        kind: "skill",
        label: "Market pulse sentezi",
        skillRef: "market-pulse-report",
      },
      {
        id: "s3",
        kind: "notify",
        label: "Slack'e brief gönder",
        channel: "slack",
        target: "#trading-daily",
      },
    ],
  },
  {
    id: "wf-weekly-exec-dashboard",
    workspaceId: "ws-ferhan-core",
    departmentId: "dept-exec",
    name: "weekly-exec-dashboard",
    cadence: "Cuma · 18:00 TR",
    nextRun: "Cuma 18:00",
    lastStatus: "success",
    steps: 6,
    description: "Haftanın sonunda tüm domain'lerden veri toplayıp exec review üretir.",
    trigger: {
      kind: "schedule",
      cron: "0 18 * * 5",
      timezone: "Europe/Istanbul",
    },
    stepsDetail: [
      {
        id: "s1",
        kind: "skill",
        label: "Trading özeti al",
        skillRef: "market-pulse-report",
      },
      {
        id: "s2",
        kind: "skill",
        label: "Ops sağlığı al",
        skillRef: "meeting-notes-synthesizer",
      },
      {
        id: "s3",
        kind: "skill",
        label: "Sales pipeline al",
        skillRef: "lead-enrichment",
      },
      {
        id: "s4",
        kind: "skill",
        label: "Haftalık biz review",
        skillRef: "weekly-biz-review",
      },
      {
        id: "s5",
        kind: "integration",
        label: "Notion dashboard güncelle",
        integration: "notion",
        target: "Exec Review DB",
      },
      {
        id: "s6",
        kind: "notify",
        label: "Slack'e özet düş",
        channel: "slack",
        target: "#leadership",
      },
    ],
  },
  {
    id: "wf-sprint-status-roundup",
    workspaceId: "ws-ferhan-core",
    departmentId: "dept-ops",
    name: "sprint-status-roundup",
    cadence: "Cuma · 16:00 TR",
    nextRun: "Cuma 16:00",
    lastStatus: "running",
    steps: 4,
    description: "Sprint sağlığı ve açık ticketları Cuma öğleden sonra konsolide eder.",
    trigger: {
      kind: "schedule",
      cron: "0 16 * * 5",
      timezone: "Europe/Istanbul",
    },
    stepsDetail: [
      {
        id: "s1",
        kind: "integration",
        label: "Linear issue'ları çek",
        integration: "linear",
        note: "aktif sprint",
      },
      {
        id: "s2",
        kind: "skill",
        label: "Notları sentezle",
        skillRef: "meeting-notes-synthesizer",
      },
      {
        id: "s3",
        kind: "integration",
        label: "Notion'a kaydet",
        integration: "notion",
        target: "Sprint Log",
      },
      {
        id: "s4",
        kind: "notify",
        label: "Slack'e özet",
        channel: "slack",
        target: "#ops-weekly",
      },
    ],
  },
  {
    id: "wf-inbound-lead-triage",
    workspaceId: "ws-ferhan-core",
    departmentId: "dept-sales",
    name: "inbound-lead-triage",
    cadence: "Webhook tetikli",
    nextRun: "Anlık",
    lastStatus: "pending-approval",
    steps: 5,
    description: "Form webhook'tan gelen yeni lead'i zenginleştirip onay kuyruğuna düşürür.",
    trigger: {
      kind: "webhook",
      webhookPath: "/hooks/lead-form",
    },
    stepsDetail: [
      {
        id: "s1",
        kind: "skill",
        label: "Lead enrichment",
        skillRef: "lead-enrichment",
      },
      {
        id: "s2",
        kind: "integration",
        label: "HubSpot CRM'ye yaz",
        integration: "hubspot",
        target: "Contacts",
      },
      {
        id: "s3",
        kind: "skill",
        label: "Outreach taslağı hazırla",
        skillRef: "lead-enrichment",
      },
      {
        id: "s4",
        kind: "approval",
        label: "external-send onayı",
        note: "Gmail draft insan onayından geçer",
      },
      {
        id: "s5",
        kind: "notify",
        label: "Slack'e ping at",
        channel: "slack",
        target: "#sales-inbound",
      },
    ],
  },
];

export const goals: Goal[] = [
  {
    id: "goal-leverage",
    workspaceId: "ws-ferhan-core",
    title: "Haftalık 10+ saat insan emeği kazan",
    metric: "Kazanılan insan saati / hafta",
    target: 10,
    current: 7.4,
    unit: "saat",
    trajectory: "on-track",
    cadence: "weekly",
    owner: "Ferhan Y.",
    linkedAgentIds: ["agent-ops-coordinator", "agent-business-exec"],
    linkedSkillIds: ["skill-meeting-notes", "skill-weekly-biz"],
    linkedThemeIds: ["st-1"],
    history: [1.2, 2.0, 2.8, 3.3, 4.1, 4.6, 5.2, 5.7, 6.0, 6.8, 7.1, 7.4],
  },
  {
    id: "goal-error-rate",
    workspaceId: "ws-ferhan-core",
    title: "Agent hata oranını %5'in altına çek",
    metric: "Hata / 100 çağrı",
    target: 5,
    current: 11,
    unit: "%",
    invert: true,
    trajectory: "at-risk",
    cadence: "weekly",
    owner: "Ferhan Y.",
    linkedAgentIds: ["agent-sales-assistant"],
    linkedSkillIds: ["skill-lead-enrichment"],
    linkedThemeIds: ["st-1", "st-2"],
    history: [18, 17, 16, 14, 13, 12, 13, 14, 13, 12, 12, 11],
  },
  {
    id: "goal-skill-velocity",
    workspaceId: "ws-ferhan-core",
    title: "Ayda 3+ yeni skill merge et",
    metric: "Merge olan skill PR'ı / ay",
    target: 3,
    current: 2,
    unit: "PR",
    trajectory: "on-track",
    cadence: "monthly",
    owner: "Ferhan Y.",
    linkedAgentIds: [],
    linkedSkillIds: [],
    linkedThemeIds: ["st-3"],
    history: [0, 1, 1, 0, 2, 2, 1, 2, 3, 2, 2, 2],
  },
  {
    id: "goal-trading-pnl",
    workspaceId: "ws-trading-desk",
    title: "Paper PnL'ı 3 ayda +%12'ye çıkar",
    metric: "Portföy getirisi",
    target: 12,
    current: 4.8,
    unit: "%",
    trajectory: "on-track",
    cadence: "weekly",
    owner: "Ferhan Y.",
    linkedAgentIds: ["agent-trading-analyst"],
    linkedSkillIds: ["skill-market-pulse"],
    linkedThemeIds: ["st-t1"],
    history: [0.3, 0.6, 1.1, 1.4, 1.9, 2.3, 2.8, 3.2, 3.6, 4.0, 4.4, 4.8],
  },
  {
    id: "goal-trading-risk",
    workspaceId: "ws-trading-desk",
    title: "Maksimum drawdown'ı %8'in altında tut",
    metric: "Max drawdown",
    target: 8,
    current: 9.5,
    unit: "%",
    invert: true,
    trajectory: "at-risk",
    cadence: "weekly",
    owner: "Ferhan Y.",
    linkedAgentIds: ["agent-trading-analyst"],
    linkedSkillIds: [],
    linkedThemeIds: ["st-t1", "st-t2"],
    history: [6.2, 6.5, 7.1, 7.4, 8.2, 8.8, 9.1, 8.9, 9.3, 9.4, 9.5, 9.5],
  },
  {
    id: "goal-content-publish",
    workspaceId: "ws-content-studio",
    title: "Haftada 2+ özgün yazı yayınla",
    metric: "Yayınlanan yazı / hafta",
    target: 2,
    current: 1.3,
    unit: "yazı",
    trajectory: "at-risk",
    cadence: "weekly",
    owner: "Ferhan Y.",
    linkedAgentIds: ["agent-content-producer"],
    linkedSkillIds: ["skill-research-synthesis"],
    linkedThemeIds: ["st-c1"],
    history: [0.5, 0.7, 1.0, 1.2, 1.4, 1.3, 1.5, 1.3, 1.2, 1.4, 1.3, 1.3],
  },
];

export const oracleSuggestions: OracleSuggestion[] = [
  {
    id: "ora-1",
    workspaceId: "ws-ferhan-core",
    kind: "gap",
    priority: "high",
    title: "Sales departmanında lead-scoring skill'i eksik",
    rationale:
      "lead-enrichment son 7 günde 23 kez çalıştı, ama hangi lead'e önce dokunulacağı manuel kararla belirleniyor. Pipeline forecast doğruluğu bu yüzden düşüyor.",
    target: "Yeni skill: lead-scorer.yaml  (owner: sales-assistant)",
    createdAt: "2026-04-21T06:00:00Z",
  },
  {
    id: "ora-2",
    workspaceId: "ws-ferhan-core",
    kind: "strategy",
    priority: "medium",
    title: "Vizyon 'içerik liderliği' diyor ama Content Studio bu workspace'de yok",
    rationale:
      "Şirket vizyonunda içerik öne çıkıyor; fakat Ferhan · Core workspace'inde content-producer yok. Ya ayrı workspace'i linkle ya da bu workspace'e content-producer ekle.",
    target: "Link / Add agent: content-producer",
    createdAt: "2026-04-21T06:00:00Z",
  },
  {
    id: "ora-3",
    workspaceId: "ws-ferhan-core",
    kind: "ops",
    priority: "medium",
    title: "Sprint roundup var ama retrospektif workflow'u yok",
    rationale:
      "Son 3 haftadır ops-coordinator çıktılarında aynı hata paterni (eksik aksiyon sahibi) tekrar etti. Retro olmadığı için iyileşme döngüsü kapanmıyor.",
    target: "Yeni workflow: weekly-retro.yaml",
    createdAt: "2026-04-20T06:00:00Z",
  },
  {
    id: "ora-4",
    workspaceId: "ws-ferhan-core",
    kind: "risk",
    priority: "high",
    title: "lead-enrichment skill'inde golden test kırılmış",
    rationale:
      "Son model sürümünden sonra çıktı formatı %12 sapıyor. Üretim tetiklemelerini duraklat ya da skill'i güncelle.",
    target: "Golden output'u güncelle veya skill'i quarantine'e al",
    createdAt: "2026-04-22T05:30:00Z",
  },
];

export const activityFeed: ActivityEvent[] = [
  {
    id: "act-1",
    workspaceId: "ws-ferhan-core",
    at: "2026-04-22T09:14:00Z",
    actor: "trading-analyst",
    verb: "tamamladı",
    object: "daily-market-briefing → #trading-daily",
    status: "ok",
  },
  {
    id: "act-2",
    workspaceId: "ws-ferhan-core",
    at: "2026-04-22T08:42:00Z",
    actor: "ops-coordinator",
    verb: "özetledi",
    object: "Proje Matrix Kick-off toplantısı (11 aksiyon çıkarıldı)",
    status: "ok",
  },
  {
    id: "act-3",
    workspaceId: "ws-ferhan-core",
    at: "2026-04-22T08:18:00Z",
    actor: "sales-assistant",
    verb: "onay bekliyor",
    object: "Outreach taslağı → 3 lead için Gmail draft",
    status: "waiting",
  },
  {
    id: "act-4",
    workspaceId: "ws-ferhan-core",
    at: "2026-04-22T07:55:00Z",
    actor: "oracle",
    verb: "önerdi",
    object: "lead-scorer skill'i (gerekçe: pipeline forecast sapması)",
    status: "ok",
  },
  {
    id: "act-5",
    workspaceId: "ws-ferhan-core",
    at: "2026-04-21T18:02:00Z",
    actor: "business-exec",
    verb: "tamamladı",
    object: "Haftalık exec dashboard v12",
    status: "ok",
  },
  {
    id: "act-6",
    workspaceId: "ws-ferhan-core",
    at: "2026-04-21T16:30:00Z",
    actor: "sales-assistant",
    verb: "hata aldı",
    object: "lead-enrichment golden test farkı %12",
    status: "failed",
  },
];

export const approvals: ApprovalItem[] = [
  {
    id: "ap-1",
    workspaceId: "ws-ferhan-core",
    agent: "sales-assistant",
    channel: "gmail",
    title: "Outreach taslağı · Acme Corp CEO'suna",
    preview:
      "Merhaba Ayşe Hanım, geçen hafta Boğaziçi Venture Day'de tanıştığımız Matrix platformunu kısaca anımsatmak istedim…",
    recipient: "ayse.kaya@acme.com",
    createdAt: "2026-04-23T09:14:00Z",
    priority: "high",
  },
  {
    id: "ap-2",
    workspaceId: "ws-ferhan-core",
    agent: "sales-assistant",
    channel: "gmail",
    title: "Follow-up · Flex Labs pazarlama müdürü",
    preview:
      "Can Bey, geçen günkü demodan sonra çerçeve dokümanını gönderiyorum. Üç noktaya dikkatinizi çekmek istedim…",
    recipient: "can@flexlabs.io",
    createdAt: "2026-04-23T08:48:00Z",
    priority: "medium",
  },
  {
    id: "ap-3",
    workspaceId: "ws-ferhan-core",
    agent: "business-exec",
    channel: "slack",
    title: "Haftalık exec dashboard v13 → #leadership",
    preview:
      "Hafta 17 özeti: 3 hedef rotada, 1 risk altında, Oracle 9 öneri üretti (2'si kabul edildi). Detaylar thread'de…",
    recipient: "#leadership",
    createdAt: "2026-04-23T08:31:00Z",
    priority: "low",
  },
  {
    id: "ap-4",
    workspaceId: "ws-trading-desk",
    agent: "trading-analyst",
    channel: "transfer",
    title: "Paper trade kaydı → portföy hareketi BTC",
    preview: "BUY 0.12 BTC @ 103,420 · TradingView sinyali #4128",
    recipient: "paper-portfolio",
    createdAt: "2026-04-23T09:02:00Z",
    priority: "medium",
  },
];

export const auditLog: AuditEvent[] = [
  {
    id: "au-1",
    workspaceId: "ws-ferhan-core",
    at: "2026-04-23T09:14:00Z",
    actor: "trading-analyst",
    action: "skill.run",
    target: "market-pulse-report",
    result: "ok",
    durationMs: 4150,
    tokens: 2840,
    traceId: "tr-a32f1",
  },
  {
    id: "au-2",
    workspaceId: "ws-ferhan-core",
    at: "2026-04-23T08:42:00Z",
    actor: "ops-coordinator",
    action: "skill.run",
    target: "meeting-notes-synthesizer",
    result: "ok",
    durationMs: 6420,
    tokens: 4120,
    traceId: "tr-b88e2",
  },
  {
    id: "au-3",
    workspaceId: "ws-ferhan-core",
    at: "2026-04-23T08:18:00Z",
    actor: "sales-assistant",
    action: "external-send.queue",
    target: "gmail → ayse.kaya@acme.com",
    result: "warn",
    durationMs: 820,
    traceId: "tr-c41aa",
  },
  {
    id: "au-4",
    workspaceId: "ws-ferhan-core",
    at: "2026-04-23T07:55:00Z",
    actor: "oracle",
    action: "scan.workspace",
    target: "ferhan-core (9 öneri)",
    result: "ok",
    durationMs: 11240,
    traceId: "tr-d12ff",
  },
  {
    id: "au-5",
    workspaceId: "ws-ferhan-core",
    at: "2026-04-22T18:02:00Z",
    actor: "business-exec",
    action: "skill.run",
    target: "weekly-biz-review",
    result: "ok",
    durationMs: 21030,
    tokens: 8820,
    traceId: "tr-e7001",
  },
  {
    id: "au-6",
    workspaceId: "ws-ferhan-core",
    at: "2026-04-22T16:30:00Z",
    actor: "sales-assistant",
    action: "skill.run",
    target: "lead-enrichment",
    result: "fail",
    durationMs: 2410,
    tokens: 1240,
    traceId: "tr-f8812",
  },
  {
    id: "au-7",
    workspaceId: "ws-ferhan-core",
    at: "2026-04-22T14:11:00Z",
    actor: "sales-assistant",
    action: "skill.run",
    target: "lead-enrichment",
    result: "fail",
    durationMs: 2300,
    tokens: 1180,
    traceId: "tr-g2234",
  },
  {
    id: "au-8",
    workspaceId: "ws-ferhan-core",
    at: "2026-04-22T11:02:00Z",
    actor: "ops-coordinator",
    action: "workflow.run",
    target: "sprint-status-roundup",
    result: "ok",
    durationMs: 18440,
    tokens: 6420,
    traceId: "tr-h5511",
  },
  {
    id: "au-9",
    workspaceId: "ws-ferhan-core",
    at: "2026-04-22T09:45:00Z",
    actor: "orchestrator",
    action: "task.delegate",
    target: "→ ops-coordinator",
    result: "ok",
    durationMs: 312,
    traceId: "tr-i7788",
  },
  {
    id: "au-10",
    workspaceId: "ws-ferhan-core",
    at: "2026-04-21T17:22:00Z",
    actor: "sales-assistant",
    action: "skill.run",
    target: "lead-enrichment",
    result: "warn",
    durationMs: 2820,
    tokens: 1340,
    traceId: "tr-j9901",
  },
  {
    id: "au-11",
    workspaceId: "ws-trading-desk",
    at: "2026-04-23T09:02:00Z",
    actor: "trading-analyst",
    action: "external-send.queue",
    target: "paper-portfolio BUY 0.12 BTC",
    result: "warn",
    durationMs: 450,
    traceId: "tr-k1102",
  },
  {
    id: "au-12",
    workspaceId: "ws-trading-desk",
    at: "2026-04-23T08:30:00Z",
    actor: "trading-analyst",
    action: "skill.run",
    target: "market-pulse-report",
    result: "ok",
    durationMs: 3980,
    tokens: 2610,
    traceId: "tr-l2215",
  },
];
