/**
 * The Operator — Matrix'in görev (task) yönetim omurgası.
 *
 * Filmdeki Tank'ın rolü: Nebuchadnezzar gemisinde kalır, crew'un hem
 * dijital (Matrix içi) hem fiziksel (gemi üzerindeki) görevlerini
 * koordine eder. Bu modül aynı şekilde:
 *
 *   - DİJİTAL task'ler: agent invocation, blog post draft, PR review,
 *     email follow-up, skill forge, workflow tetikleme
 *   - FİZİKSEL task'ler: supplier görüşmesi, kargo etiketi basma,
 *     ofis malzeme tedariki, event organizasyonu, human meeting
 *
 *   - Dış entegrasyon: Linear/Notion/Asana/Trello/Jira'dan
 *     two-way sync (pull + push)
 *   - Cross-link: Rock milestone, Issue action, Workflow step ile
 *     bağlanabilir
 */

export type TaskRealm = "digital" | "physical";
export type TaskStatus = "todo" | "doing" | "review" | "done" | "blocked";
export type TaskPriority = "p0" | "p1" | "p2" | "p3";
export type TaskOwnerKind = "agent" | "human";

export type TaskSource =
  | "matrix" // native Matrix task
  | "linear"
  | "notion"
  | "asana"
  | "trello"
  | "jira"
  | "github"
  | "oracle"; // generated by Oracle suggestion

export interface Task {
  id: string;
  workspaceId: string;
  title: string;
  description?: string;
  realm: TaskRealm;
  status: TaskStatus;
  priority: TaskPriority;
  ownerName: string;
  ownerKind: TaskOwnerKind;
  tags: string[];
  // Dates (ISO)
  createdAtIso: string;
  dueAtIso?: string;
  startedAtIso?: string;
  completedAtIso?: string;
  // Integration tracking
  source: TaskSource;
  externalId?: string;
  externalUrl?: string;
  lastSyncedAtIso?: string;
  // Cross-linking with other Matrix entities
  relatedRockId?: string;
  relatedIssueId?: string;
  relatedWorkflowId?: string;
  relatedAgentId?: string;
  // Effort estimation
  estimatedMinutes?: number;
  actualMinutes?: number;
  // Approval requirement (for external-send tasks)
  requiresApproval?: boolean;
}

export interface TaskBoardColumn {
  status: TaskStatus;
  label: string;
  tone: "ion" | "nebula" | "quantum" | "solar" | "crimson";
}

export const boardColumns: TaskBoardColumn[] = [
  { status: "todo", label: "To Do", tone: "ion" },
  { status: "doing", label: "Doing", tone: "nebula" },
  { status: "review", label: "Review", tone: "solar" },
  { status: "done", label: "Done", tone: "quantum" },
  { status: "blocked", label: "Blocked", tone: "crimson" },
];

export const sourceLabels: Record<TaskSource, string> = {
  matrix: "Matrix",
  linear: "Linear",
  notion: "Notion",
  asana: "Asana",
  trello: "Trello",
  jira: "Jira",
  github: "GitHub",
  oracle: "Oracle",
};

export const priorityMeta: Record<
  TaskPriority,
  { label: string; tone: "crimson" | "solar" | "ion" | "text-muted" }
> = {
  p0: { label: "P0 · Kritik", tone: "crimson" },
  p1: { label: "P1 · Yüksek", tone: "solar" },
  p2: { label: "P2 · Normal", tone: "ion" },
  p3: { label: "P3 · Düşük", tone: "text-muted" },
};

// ---------------------------------------------------------------------------
// Seed — realistic mix of digital + physical tasks across workspaces
// ---------------------------------------------------------------------------

const now = new Date("2026-04-23T12:00:00Z").getTime();
const hrs = (h: number) => new Date(now + h * 3600_000).toISOString();
const days = (d: number) => new Date(now + d * 86400_000).toISOString();

export const tasks: Task[] = [
  // ═══════ Ferhan · Core ═══════════════════════════════════════════════════
  {
    id: "t-001",
    workspaceId: "ws-ferhan-core",
    title: "Haftalık Oracle önerilerini review et (17 yeni)",
    description:
      "3 yüksek öncelik önerisi insan kararı bekliyor — kabul/yoksay/incele",
    realm: "digital",
    status: "todo",
    priority: "p1",
    ownerName: "Ferhan Y.",
    ownerKind: "human",
    tags: ["oracle", "review"],
    createdAtIso: hrs(-2),
    dueAtIso: days(1),
    source: "oracle",
    estimatedMinutes: 20,
  },
  {
    id: "t-002",
    workspaceId: "ws-ferhan-core",
    title: "CS blueprint 2. aşama — 5 agent canlıya al",
    description: "Rock-q2-01 milestone, tüm skill'ler hazır, deploy sırası",
    realm: "digital",
    status: "doing",
    priority: "p0",
    ownerName: "Ferhan Y.",
    ownerKind: "human",
    tags: ["blueprint", "deploy", "cs"],
    createdAtIso: days(-2),
    dueAtIso: days(9),
    startedAtIso: hrs(-5),
    source: "matrix",
    relatedRockId: "rock-q2-01",
    estimatedMinutes: 180,
  },
  {
    id: "t-003",
    workspaceId: "ws-ferhan-core",
    title: "Matrix.ferhan.co domain'i Railway'e bağla",
    description: "DNS CNAME + Cloudflare Access kuralı",
    realm: "physical",
    status: "todo",
    priority: "p1",
    ownerName: "Ferhan Y.",
    ownerKind: "human",
    tags: ["devops", "domain"],
    createdAtIso: hrs(-1),
    dueAtIso: days(2),
    source: "matrix",
    estimatedMinutes: 45,
  },
  {
    id: "t-004",
    workspaceId: "ws-ferhan-core",
    title: "Outbound email taslakları — 8 prospect Seraph onayında",
    description: "Business Exec ajanı hazırladı, approval queue'da bekliyor",
    realm: "digital",
    status: "review",
    priority: "p1",
    ownerName: "Business Exec",
    ownerKind: "agent",
    tags: ["outbound", "approval-pending"],
    createdAtIso: hrs(-4),
    source: "matrix",
    relatedAgentId: "ag-business-exec",
    requiresApproval: true,
    estimatedMinutes: 15,
  },
  {
    id: "t-005",
    workspaceId: "ws-ferhan-core",
    title: "Co-founder ile öğle görüşmesi — Cumartesi 13:00",
    description: "Matrix 2026 Q2 roadmap reviewü · Kadıköy Moda Kafe",
    realm: "physical",
    status: "todo",
    priority: "p1",
    ownerName: "Ferhan Y.",
    ownerKind: "human",
    tags: ["meeting", "strategy"],
    createdAtIso: days(-1),
    dueAtIso: days(3),
    source: "notion",
    externalId: "notion://abc123",
    externalUrl: "https://notion.so/task/abc123",
    lastSyncedAtIso: hrs(-3),
    estimatedMinutes: 120,
  },
  {
    id: "t-006",
    workspaceId: "ws-ferhan-core",
    title: "Haftalık L10 meeting — Pazartesi 09:30",
    description: "Captain's Log ritüeli — scorecard + rock + issues IDS",
    realm: "digital",
    status: "todo",
    priority: "p1",
    ownerName: "Ferhan Y.",
    ownerKind: "human",
    tags: ["eos", "ritual"],
    createdAtIso: days(-7),
    dueAtIso: days(4),
    source: "matrix",
    estimatedMinutes: 90,
  },
  {
    id: "t-007",
    workspaceId: "ws-ferhan-core",
    title: "Haftalık blog post üret — 'Holdco OS' konusu",
    description:
      "content-writer ajanı draft, Ferhan review, Beehiiv'e Perşembe publish",
    realm: "digital",
    status: "doing",
    priority: "p2",
    ownerName: "content-writer",
    ownerKind: "agent",
    tags: ["content", "weekly"],
    createdAtIso: hrs(-8),
    dueAtIso: days(2),
    startedAtIso: hrs(-6),
    source: "matrix",
    estimatedMinutes: 60,
  },
  {
    id: "t-008",
    workspaceId: "ws-ferhan-core",
    title: "Agent hata paternlerini golden test'e çevir (Rock Q2-04)",
    description: "3 pattern tespit edildi, test coverage +%40 hedef",
    realm: "digital",
    status: "blocked",
    priority: "p0",
    ownerName: "Ops Coordinator",
    ownerKind: "agent",
    tags: ["testing", "rock"],
    createdAtIso: days(-5),
    dueAtIso: days(12),
    source: "matrix",
    relatedRockId: "rock-q2-04",
    estimatedMinutes: 480,
  },
  {
    id: "t-009",
    workspaceId: "ws-ferhan-core",
    title: "HubSpot rate-limit kotasını paid tier'a yükselt",
    description: "Issue-02 çözümü — 48 saat SLA",
    realm: "physical",
    status: "doing",
    priority: "p1",
    ownerName: "Ferhan Y.",
    ownerKind: "human",
    tags: ["connector", "billing"],
    createdAtIso: hrs(-16),
    dueAtIso: days(2),
    startedAtIso: hrs(-4),
    source: "matrix",
    relatedIssueId: "iss-02",
    estimatedMinutes: 30,
  },
  {
    id: "t-010",
    workspaceId: "ws-ferhan-core",
    title: "Kargo firmasıyla haftalık shipping rate görüşmesi",
    description: "Trading Desk fiziksel ürün tedarikçisi — Yurtiçi Kargo",
    realm: "physical",
    status: "done",
    priority: "p2",
    ownerName: "Ferhan Y.",
    ownerKind: "human",
    tags: ["vendor", "shipping"],
    createdAtIso: days(-3),
    completedAtIso: days(-1),
    source: "linear",
    externalId: "FER-142",
    externalUrl: "https://linear.app/ferhan/issue/FER-142",
    lastSyncedAtIso: hrs(-24),
    estimatedMinutes: 30,
    actualMinutes: 22,
  },

  // ═══════ Trading Desk ═══════════════════════════════════════════════════
  {
    id: "t-td-001",
    workspaceId: "ws-trading-desk",
    title: "Paper-trade sonuçları — 14g backtest raporu",
    description: "trading-analyst ajanı üretti, human onayı gerek",
    realm: "digital",
    status: "review",
    priority: "p0",
    ownerName: "Ferhan Y.",
    ownerKind: "human",
    tags: ["trading", "review", "risk"],
    createdAtIso: hrs(-6),
    dueAtIso: hrs(18),
    source: "matrix",
    estimatedMinutes: 45,
  },
  {
    id: "t-td-002",
    workspaceId: "ws-trading-desk",
    title: "Daily market briefing — sabah 08:00 push",
    description: "trading-analyst ajanı #trading-briefings kanalına yazacak",
    realm: "digital",
    status: "todo",
    priority: "p1",
    ownerName: "trading-analyst",
    ownerKind: "agent",
    tags: ["daily", "briefing"],
    createdAtIso: days(-1),
    dueAtIso: hrs(20),
    source: "matrix",
    estimatedMinutes: 10,
  },
  {
    id: "t-td-003",
    workspaceId: "ws-trading-desk",
    title: "Binance API key rotation",
    description: "90 günlük security cycle — yeni key üret, env güncelle",
    realm: "physical",
    status: "todo",
    priority: "p1",
    ownerName: "Ferhan Y.",
    ownerKind: "human",
    tags: ["security", "rotation"],
    createdAtIso: days(-2),
    dueAtIso: days(1),
    source: "matrix",
    requiresApproval: true,
    estimatedMinutes: 25,
  },

  // ═══════ Content Studio ══════════════════════════════════════════════════
  {
    id: "t-cs-001",
    workspaceId: "ws-content-studio",
    title: "Podcast ep #12 — transcript + show notes üret",
    description:
      "audio-transcriber → summary-writer → notion page. Cmt yayın.",
    realm: "digital",
    status: "doing",
    priority: "p1",
    ownerName: "audio-transcriber",
    ownerKind: "agent",
    tags: ["podcast", "content"],
    createdAtIso: hrs(-10),
    dueAtIso: days(2),
    startedAtIso: hrs(-8),
    source: "matrix",
    estimatedMinutes: 40,
  },
  {
    id: "t-cs-002",
    workspaceId: "ws-content-studio",
    title: "Studio mikrofon kablosu — Teknosa'dan al",
    description: "Shure SM7B XLR 3m · fiziksel ekipman gap'i",
    realm: "physical",
    status: "todo",
    priority: "p2",
    ownerName: "Ferhan Y.",
    ownerKind: "human",
    tags: ["equipment"],
    createdAtIso: hrs(-20),
    dueAtIso: days(3),
    source: "trello",
    externalId: "TRL-CS-88",
    externalUrl: "https://trello.com/c/abc",
    lastSyncedAtIso: hrs(-12),
    estimatedMinutes: 45,
  },
  {
    id: "t-cs-003",
    workspaceId: "ws-content-studio",
    title: "Sponsor outreach batch — 5 AI founder newsletter",
    description: "outreach-writer ajanı draft'lıyor, Seraph onayından geçecek",
    realm: "digital",
    status: "review",
    priority: "p1",
    ownerName: "outreach-writer",
    ownerKind: "agent",
    tags: ["sponsor", "outbound", "approval-pending"],
    createdAtIso: hrs(-3),
    source: "matrix",
    requiresApproval: true,
    estimatedMinutes: 30,
  },
  {
    id: "t-cs-004",
    workspaceId: "ws-content-studio",
    title: "Beehiiv sponsor kontrat taslağı — editör review",
    description: "İlk 2 prospect için standart sponsor kontrat taslağı",
    realm: "digital",
    status: "todo",
    priority: "p2",
    ownerName: "Ferhan Y.",
    ownerKind: "human",
    tags: ["legal", "sponsor"],
    createdAtIso: hrs(-5),
    dueAtIso: days(5),
    source: "notion",
    externalId: "notion://cs-contract-draft",
    externalUrl: "https://notion.so/cs-contract-draft",
    lastSyncedAtIso: hrs(-5),
    estimatedMinutes: 60,
  },
  {
    id: "t-cs-005",
    workspaceId: "ws-content-studio",
    title: "Haftalık newsletter — 'AI Matrix #24' Beehiiv publish",
    description:
      "content-researcher → writer → fact-checker → Gemini audit → publish",
    realm: "digital",
    status: "done",
    priority: "p1",
    ownerName: "content-writer",
    ownerKind: "agent",
    tags: ["newsletter", "weekly"],
    createdAtIso: days(-7),
    completedAtIso: days(-2),
    source: "matrix",
    estimatedMinutes: 120,
    actualMinutes: 95,
  },
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

export function tasksForWorkspace(wsId: string): Task[] {
  return tasks.filter((t) => t.workspaceId === wsId);
}

export function tasksByStatus(tasks: Task[]): Record<TaskStatus, Task[]> {
  const out: Record<TaskStatus, Task[]> = {
    todo: [],
    doing: [],
    review: [],
    done: [],
    blocked: [],
  };
  for (const t of tasks) out[t.status].push(t);
  return out;
}

export function tasksByRealm(tasks: Task[]): Record<TaskRealm, Task[]> {
  return {
    digital: tasks.filter((t) => t.realm === "digital"),
    physical: tasks.filter((t) => t.realm === "physical"),
  };
}

/**
 * "Overdue" — dueAtIso geçmiş ve henüz done değil.
 */
export function isOverdue(t: Task, nowIso: string = new Date().toISOString()): boolean {
  if (!t.dueAtIso || t.status === "done") return false;
  return t.dueAtIso < nowIso;
}
